### PR TITLE
Fixes and refactoring of CI files

### PR DESCRIPTION
**Pull request by gaby**
- Update all the CI files
- Add rules to avoid running jobs when modifying config files.

### CODE REVIEW

**Comment by gaby** [comment]
@ReneWerner87 @efectn Any idea why the windows ci now fails? It has been failing for a while now. The old CI's for `govulncheck`  were set to always run thus why they show here too...

**Comment by gaby** [comment]
> @ReneWerner87 @efectn Any idea why the windows ci now fails? It has been failing for a while now. The old CI's for `govulncheck` were set to always run thus why they show here too...

Nevermind, fixed the windows failure. This PR is ready :-)

**Review by ReneWerner87 — APPROVED** [review]

**Review by efectn — APPROVED** [review]

**Comment by gaby** [comment]
@ReneWerner87 This one is ready to merge. It will close all the other pending PR's

**Comment by ReneWerner87** [comment]
Will do it later (currently on the road)

**Pull request merged**
